// Ralf Poeppel, 2026
//
// This file implements matrices of bits of arbitrary size.

package gf2vs

import (
	"fmt"
	"math/big"
	"math/bits"
	"slices"
)

// BitMatrix the type of a bit matrix.
// We use an array of big.Int representing the matrix.
// Smallest bit is the rightmost column.
type BitMatrix []*big.Int

// String returns the decimal representation of x as generated by x.Text(10, "\n").
func (bm *BitMatrix) String() string {
	return bm.Text(10, "\n")
}

// Text convert bm to a string, use sep as separator of rows.
func (bm *BitMatrix) Text(base int, sep string) string {
	rw := make([]string, len(*bm))
	ln := 0
	for i, row := range *bm {
		rw[i] = row.Text(base) + sep
		l := len(rw[i])
		if l > ln {
			ln = l
		}
	}

	r := ""
	for _, row := range rw {
		r += fmt.Sprintf("%0[1]*[2]s", ln, row)
	}
	return r
}

// Cmp compares x and y and returns:
//   - -1 if x < y;
//   - 0 if x == y;
//   - +1 if x > y.
//
// First the count of rows is compared. The matrix with less rows is considered smaller.
// If both matrices have the same number of rows, the rows are compared sequentially,
// starting at index 0, until one row is not equal to the other. The result of comparing
// the first non-matching row is returned.
func (x *BitMatrix) Cmp(y *BitMatrix) (r int) {
	c := len(*x) - len(*y)
	switch {
	case c < 0:
		return -1
	case c > 0:
		return 1
	}
	return slices.CompareFunc(*x, *y, func(a, b *big.Int) int {
		return a.Cmp(b)
	})
}

// Set sets z to x and returns z.
func (z *BitMatrix) Set(x *BitMatrix) *BitMatrix {
	if z == x {
		return z
	}
	zm := make(BitMatrix, len(*x))
	for i, r := range *x {
		zm[i] = big.NewInt(0).Set(r)
	}
	z = &zm
	return z
}

// RowReducedEcholonForm convert a binary Matrix to row reduced echolon form,
// and return the rank of the matrix, for mr bits on right side.
// If last line has only values on right side we have a contradiction,
// ok will be false.
func (bm *BitMatrix) RowReducedEcholonForm(mr int) (rank int, ok bool) {
	bmat := *bm
	ok = true
	for r := range bmat {
		// search pivot row
		pr := r
		nr := r + 1
		for i, rs := range bmat[nr:] {
			if rs.Cmp(bmat[pr]) == 1 {
				pr = i + nr
			}
		}
		// swap rows if pivot row is larger as current row
		if r < pr {
			bmat[r], bmat[pr] = bmat[pr], bmat[r]
		}
		// pivot row
		rp := bmat[r]
		// position of pivot bit in Int
		lpr := rp.BitLen() - 1

		// test on iteration end
		if lpr < 0 {
			// remaining rows are zero rows, we are done
			*bm = (*bm)[:r]
			return r, ok
		}
		if lpr < mr {
			// left side is 0, right > 0, contradiction
			ok = false
		}

		// add pivot row to all remaining rows with pivot bit set
		for i := r + 1; i < len(*bm); i++ {
			rw := (*bm)[i]
			if rw.Bit(lpr) != 0 {
				rw.Xor(rw, rp)
			}
		}
		// add pivot row to all previous rows with pivot bit set
		for i := 0; i < r; i++ {
			rw := (*bm)[i]
			if rw.Bit(lpr) != 0 {
				rw.Xor(rw, rp)
			}
		}
	}
	return len(*bm), ok
}

// LeftRightSplitter a closure which splits a big.Int x in left and right
// right has the size of mr bits
func LeftRightSplitter(mr int) func(x *big.Int) (*big.Int, *big.Int) {
	if mr == 0 {
		return func(x *big.Int) (*big.Int, *big.Int) {
			return x, big.NewInt(0)
		}
	}
	maxR := 2<<(mr-1) - 1
	mask := big.NewInt(int64(maxR))
	return func(x *big.Int) (*big.Int, *big.Int) {
		right := big.NewInt(0).And(x, mask)
		left := big.NewInt(0).AndNot(x, mask)
		return left, right
	}
}

// XorSatSolveError holds the error messages of XorSatSolver.
type XorSatSolveError struct {
	What string
}

// Error return the error messages as string.
func (e *XorSatSolveError) Error() string {
	return fmt.Sprint(e.What)
}

// SolutionFromRref determine the solution of an extended coefficient BitMatrix
// which is in row reduced echolon form with mr right sides, result vector holds
// for each variable a value between -1 and 2**mr-1.
// The value may be 0.
// -1 is returned for rows not in row reduced echolon form and
// error is set to "Partial Solution returned".
// Maximum value of mr supported is bits.UintSize - 2
// Other errors are set on invalid input.
func (bm *BitMatrix) SolutionFromRref(mr int) ([]int, error) {
	if mr <= 0 {
		return nil, &XorSatSolveError{"No values on right side"}
	}
	if mr > bits.UintSize-1 { // bit len of int
		msg := fmt.Sprintf("#right:mr=%v to big for int on this processor", mr)
		return nil, &XorSatSolveError{msg}
	}
	ln := len(*bm)
	if ln == 0 {
		return nil, &XorSatSolveError{"Given BitMatrix has no elements"}
	}
	// check row length, need to be bigger as count of rows + bits on right side
	rowlen := (*bm)[0].BitLen()
	if rowlen < mr+ln {
		msg := fmt.Sprintf("Row length=%v to short, "+
			"#rows:ln=%v, #right:mr=%v", rowlen, ln, mr)
		return nil, &XorSatSolveError{msg}
	}

	var err error
	sol := make([]int, rowlen-mr)
	// preset solution to unknown
	for i := range sol {
		sol[i] = -1
	}
	// Bit vector with value 0 for comparisons
	zero := big.NewInt(0)
	countSol := 0
	lrSplitter := LeftRightSplitter(mr)
	one := big.NewInt(1)
	for _, r := range *bm {
		left, right := lrSplitter(r)
		compare := left.Cmp(zero)
		// test on contradiction
		if compare == 0 {
			return nil, &XorSatSolveError{"Contradiction of equations of echolon form"}
		}
		// test one bit set, see
		// https://graphics.stanford.edu/~seander/bithacks.html#DetermineIfPowerOf2
		// (r > 0) && ((r & (r - 1)) == 0)
		if left.Cmp(zero) > 0 {
			leftm1 := (big.NewInt(0)).Sub(left, one)
			leftmam1 := (big.NewInt(0)).And(left, leftm1)
			if leftmam1.Cmp(zero) == 0 {
				i := rowlen - r.BitLen()
				sol[i] = int(right.Int64()) // no overflow as mr is limited
				countSol++
			}
		}
	}

	if countSol != len(sol) {
		err = &XorSatSolveError{"Partial solution returned"}
	}
	return sol, err
}

// XorSatSolve return solution of a xor-sat problem given as bm, for m symbols
// on right side. Solution vector values are between -1 and 1<<(mr-1).
// The error Partial solution returned is returned if any variable cannot
// computed, value is -1. The rank is returned too.
// If there are contradicting equations, error is set to "Contradiction of equations of BitMatrix".
// If not all variables are determined, error is set to "Partial solution returned".
func (bm *BitMatrix) XorSatSolve(mr int) ([]int, int, error) {
	rank, ok := bm.RowReducedEcholonForm(mr)
	if !ok {
		return nil, 0, &XorSatSolveError{"Contradiction of equations of BitMatrix"}
	}
	sol, err := bm.SolutionFromRref(mr)
	return sol, rank, err
}
